include:
  - project: 'devops/gitlab/ci-script'
    file: 'docker.yaml'
# 构建步骤
stages:
  - go-build
  - docker-build

go-build:
  image: dhub.msorg.cn/library/golang:alpine
  stage: go-build
  variables:
    GOPROXY: https://gohub.msorg.cn/public/,direct
  before_script:
    - sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
    - apk add --no-cache make git
    - ls -la
  script:
    - make
    - ./skac --version
  artifacts:
    paths:
      - skac
