include:
  - project: 'devops/gitlab/ci-script'
    file: 'docker.yaml'
# 构建步骤
stages:
  - go-build
  - docker-build

go-build:
  image: dhub.msorg.cn/library/golang
  stage: go-build
  variables:
    GOPROXY: https://gohub.msorg.cn/public/,direct
  before_script:
    - ls -la
  script:
    - make
    - ./skac --version
  artifacts:
    paths:
      - skac